name: Delete Workflows Runs

on:
  workflow_dispatch:

  schedule:
    - cron: 0 1 * * *

jobs:
  Delete:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Workflows Runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 3
          keep_minimum_runs: 3
