name: Delete Workflows

on:
  workflow_dispatch:

  schedule:
    - cron: 0 0 * * *

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Workflow Runs
        uses: GitRML/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 1
          keep_minimum_runs: 3
          
      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@main
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
