name: Delete Workflows Runs

on:
  workflow_dispatch:

  schedule:
    - cron: 0 0 * * *

jobs:
  Delete:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Workflows Runs
        uses: Mattraks/delete-workflow-runs@v2.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 1
          keep_minimum_runs: 3
