name: immortalwrt-imagebuilder-23.05-SNAPSHOT

on:
  workflow_dispatch:

  schedule:
    - cron: 0 0 * * *

jobs:
  Config:
    runs-on: ubuntu-latest

    steps:
      - name: Requirements
        run: |
          wget -q https://downloads.immortalwrt.org/releases/23.05-SNAPSHOT/targets/rockchip/armv8/immortalwrt-imagebuilder-23.05-SNAPSHOT-rockchip-armv8.Linux-x86_64.tar.xz
          tar -xJf *.tar.xz
          cd immortalwrt-imagebuilder-23.05-SNAPSHOT-rockchip-armv8.Linux-x86_64
          cp -rf $GITHUB_WORKSPACE/files .
          chmod +x files/etc/rc.local
          chmod +x $GITHUB_WORKSPACE/scripts/*
          $GITHUB_WORKSPACE/scripts/preset-terminal-tools.sh
          export CONFIG_PACKAGES=$(cat $GITHUB_WORKSPACE/config/packages.config | tr -s "\n" " ")
          make image PACKAGES="$CONFIG_MINI_PACKAGES" FILES="files"
          ls -al bin/targets/$DEVICE_TARGET/$DEVICE_SUBTARGET/*
       
